name: Update pinned-gist
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  productive-box:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update productive-box
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: b689fe8ba656f515c17aad2f2f9b0ad8
          TIMEZONE: Asia/Seoul
